if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56d93c2265438',
	'title' => '404 Page',
	'fields' => array (
		array (
			'key' => 'field_56d93c2dd9c92',
			'label' => '404 Content',
			'name' => 'page_not_found',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<p>
	<strong>Did you type the URL?</strong><br />
	You may have typed the address (URL) incorrectly. Check it to make sure you\'ve got the exact right spelling, capitalization, etc.
</p>
<p>
	<strong>Did you follow a link from somewhere else at this site?</strong><br />
	If you reached this page from another part of this site.
</p>
<p>
	<strong>Did you follow a link from another site?</strong><br />
	Links from other sites can sometimes be outdated or misspelled.
</p>',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_565fca1a04d5f',
	'title' => 'Call To Action',
	'fields' => array (
		array (
			'key' => 'field_565fca246e893',
			'label' => 'Main Call To Action',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Main call to action appears as a white button below copy.	Will only display if the destination is chosen and the call to action label is entered.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_565fca376e894',
			'label' => 'Call To Action Label',
			'name' => 'call_to_action_text',
			'type' => 'text',
			'instructions' => 'If left blank, button will not show.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g, "See More", "Click Here", etc.',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_565fd40bdfb0c',
			'label' => 'Open link in new window',
			'name' => 'new_window',
			'type' => 'true_false',
			'instructions' => 'Check if you want users to be taken to this link in a new browser window / tab. Most useful for external links or downloadable assets such as PDFs.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565fcaa845ef1',
						'operator' => '==',
						'value' => 'external',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_565fcaa845ef1',
			'label' => 'Destination Type',
			'name' => 'destination_type',
			'type' => 'radio',
			'instructions' => 'Will this button go to an internal page / post / image or an external link?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'false' => 'Select...',
				'internal' => 'Internal',
				'external' => 'External',
				'archive' => 'Archive',
				'eventcategory' => 'Event Category',
				'download' => 'Download',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Select...',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_565fca416e895',
			'label' => 'CTA Internal Destination',
			'name' => 'cta_internal',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565fcaa845ef1',
						'operator' => '==',
						'value' => 'internal',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_566e3955bacc7',
			'label' => 'CTA External Destination',
			'name' => 'cta_external_destination',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565fcaa845ef1',
						'operator' => '==',
						'value' => 'external',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56686937b3868',
			'label' => 'CTA Archive Destination',
			'name' => 'cta_archive_destination',
			'type' => 'taxonomy',
			'instructions' => 'Will link to a listing of *all* posts in this taxonomy.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565fcaa845ef1',
						'operator' => '==',
						'value' => 'archive',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'target',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_56dd19c96c4c1',
			'label' => 'CTA Event Category',
			'name' => 'cta_event_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565fcaa845ef1',
						'operator' => '==',
						'value' => 'eventcategory',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'tribe_events_cat',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_56776c8e3708e',
			'label' => 'CTA Download Destination',
			'name' => 'cta_download_destination',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_565fcaa845ef1',
						'operator' => '==',
						'value' => 'download',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'attachment',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_56686d4fbcf85',
			'label' => 'Description',
			'name' => 'cta_description',
			'type' => 'textarea',
			'instructions' => 'Appears below the CTA button.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'page-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_567229d2cc197',
	'title' => 'Events',
	'fields' => array (
		array (
			'key' => 'field_567229d672da8',
			'label' => 'Event Image',
			'name' => 'event_image',
			'type' => 'image',
			'instructions' => 'Main Image that appears on event list.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tribe_events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_565bc41f4710c',
	'title' => 'Hero Image',
	'fields' => array (
		array (
			'key' => 'field_565bb64a3aab5',
			'label' => 'Featured Hero Image',
			'name' => 'featured_hero_image',
			'type' => 'image',
			'instructions' => 'Hero image that appears above post or page content. Also serves as the thumbnail for the post.
Recommended size is 1600x700.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56803bdc1fe57',
			'label' => 'Hero Image - Tablet',
			'name' => 'hero_image_tablet',
			'type' => 'image',
			'instructions' => 'Tablet version for hero image. Optional, but recommended.	Size should be 768x500.	If left blank, code will use the desktop version on tablet devices.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 768,
			'min_height' => 500,
			'min_size' => '',
			'max_width' => 768,
			'max_height' => 500,
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56803c0c1fe58',
			'label' => 'Hero Image - Mobile',
			'name' => 'hero_image_mobile',
			'type' => 'image',
			'instructions' => 'Tablet version for hero image. Optional, but recommended.	Size should be 480x350. If left blank, will use the tablet version.	 If left blank, code will use the desktop version on tablet devices.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 480,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => 480,
			'max_height' => 350,
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'page-home.php',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'tribe_venue',
			),
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'tribe_organizer',
			),
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'tribe_events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_565bc44e3fc0d',
	'title' => 'Home',
	'fields' => array (
		array (
			'key' => 'field_565bc50122170',
			'label' => 'Headline',
			'name' => 'headline',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_565bc50d22171',
			'label' => 'Subheadline',
			'name' => 'subheadline',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57b0f6b60d365',
			'label' => 'Slideshow Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_565bc45c13a5f',
			'label' => 'Hero Image Gallery',
			'name' => 'hero_image_gallery',
			'type' => 'repeater',
			'instructions' => 'Auto-Rotating Hero Image Gallery',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Image To Gallery',
			'sub_fields' => array (
				array (
					'key' => 'field_56665bc0ccf98',
					'label' => 'Gallery Image',
					'name' => 'gallery_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56803cd750ee1',
					'label' => 'Gallery Image - Tablet',
					'name' => 'gallery_image_tablet',
					'type' => 'image',
					'instructions' => 'Tablet image for galleries. Recommended size is 768x500',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => 768,
					'max_height' => 500,
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56803d0650ee2',
					'label' => 'Gallery Image - Mobile',
					'name' => 'gallery_image_mobile',
					'type' => 'image',
					'instructions' => 'Mobile image for galleries. Recommended size is 480x350',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => 480,
					'max_height' => 350,
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_57b0f78d736a9',
					'label' => 'Slide Type',
					'name' => 'slide_type',
					'type' => 'radio',
					'instructions' => 'Basic - no link, no text; Full Text With Link - Has a transparent triangle-shaped overlay for the text; Linked Image - Clicking the image in the slideshow links to a destination; CTA Button - includes a call to action button above the slideshow nav.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'basic' => 'Basic',
						'full' => 'Full Text With Link',
						'linked_image' => 'Linked Image',
						'cta' => 'CTA Button',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
				),
				array (
					'key' => 'field_56665c05ccf99',
					'label' => 'Headline',
					'name' => 'headline',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '==',
								'value' => 'full',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56665c11ccf9a',
					'label' => 'Body',
					'name' => 'body',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '==',
								'value' => 'full',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56665c15ccf9b',
					'label' => 'Call To Action Label',
					'name' => 'call_to_action_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '==',
								'value' => 'full',
							),
						),
						array (
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '==',
								'value' => 'cta',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56665f9d75e0c',
					'label' => 'Link Destination',
					'name' => 'link_destination',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '!=',
								'value' => 'basic',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'internal' => 'Internal',
						'external' => 'External',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_56665c23ccf9c',
					'label' => 'Call To Action Destination - External',
					'name' => 'call_to_action_destination_external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56665f9d75e0c',
								'operator' => '==',
								'value' => 'external',
							),
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '!=',
								'value' => 'basic',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_56665f8575e0b',
					'label' => 'Call To Action Destination - Internal',
					'name' => 'call_to_action_destination_internal',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56665f9d75e0c',
								'operator' => '==',
								'value' => 'internal',
							),
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '!=',
								'value' => 'basic',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_57b0f7d5736aa',
					'label' => 'CTA Theme',
					'name' => 'cta_theme',
					'type' => 'select',
					'instructions' => 'What color do you want the button? Default is Celeste.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57b0f78d736a9',
								'operator' => '==',
								'value' => 'cta',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'celeste' => 'Celeste',
						'white' => 'White',
						'black' => 'Black',
					),
					'default_value' => array (
						0 => 'celeste',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
			),
		),
		array (
			'key' => 'field_57b0f6cf0d366',
			'label' => 'Slideshow Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57b0f6da0d367',
			'label' => 'Enable Autoplay',
			'name' => 'autoplay',
			'type' => 'true_false',
			'instructions' => 'Select if you want your slideshow to autoplay.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
		),
		array (
			'key' => 'field_57b0f6f60d368',
			'label' => 'Slideshow Timing',
			'name' => 'slideshow_timing',
			'type' => 'text',
			'instructions' => 'How many seconds between each autoplayed slide? Default is 10 seconds.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57b0f6da0d367',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 10,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Seconds',
			'maxlength' => 2,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57b0f72a0d369',
			'label' => 'Pause On Hover',
			'name' => 'pause_on_hover',
			'type' => 'true_false',
			'instructions' => 'If checked, the slideshow will pause when user hovers his mouse over the slideshow. Useful so that the slide does not advance while user is trying to click on a link.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_57b0f6da0d367',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'format',
		7 => 'featured_image',
		8 => 'categories',
		9 => 'tags',
		10 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => 'Edit home page gallery & hero.',
));

acf_add_local_field_group(array (
	'key' => 'group_565bc5acd3618',
	'title' => 'Layouts',
	'fields' => array (
		array (
			'key' => 'field_565bc5b494d21',
			'label' => 'Layout',
			'name' => 'layout',
			'type' => 'flexible_content',
			'instructions' => 'Allows you to choose from three types of layouts that are used primarily on the homepage.
Layout types are:

Three-Up - Used to display 3 icons with content
Featured Bullet - Bullet List
Rollover Panel - panels of content with an image that appears on mouseover.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Layout',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '565bc5bcc5ffc',
					'name' => 'threeup',
					'label' => 'Three-Up Layout',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_565bc60ca1ef3',
							'label' => 'Headline',
							'name' => 'headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_565bc74aa8c82',
							'label' => 'Full Height',
							'name' => 'full_height',
							'type' => 'true_false',
							'instructions' => 'If "True", the content area takes up 100% of the screen\'s visual height. Works best on the home page.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
						),
						array (
							'key' => 'field_565bc61ca1ef4',
							'label' => 'Item',
							'name' => 'item',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 3,
							'max' => 3,
							'layout' => 'table',
							'button_label' => 'Add Item',
							'sub_fields' => array (
								array (
									'key' => 'field_565bc629a1ef5',
									'label' => 'Heading',
									'name' => 'heading',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_565bc630a1ef6',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_565bc639a1ef7',
									'label' => 'Content',
									'name' => 'content',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_565bc640a1ef8',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '565bc7e684722',
					'name' => 'featuredbullet',
					'label' => 'Featured Bullet Layout',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_565bc7f084723',
							'label' => 'Headline',
							'name' => 'headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_565bc7f884724',
							'label' => 'Full Height',
							'name' => 'full_height',
							'type' => 'true_false',
							'instructions' => 'If "True", the content area takes up 100% of the screen\'s visual height. Works best on the home page.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
						),
						array (
							'key' => 'field_565bc80c84725',
							'label' => 'Bullets',
							'name' => 'bullets',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Bullet',
							'sub_fields' => array (
								array (
									'key' => 'field_565bc82084726',
									'label' => 'Bullet Content',
									'name' => 'bullet_content',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '565bc93e7949d',
					'name' => 'rolloverpanel',
					'label' => 'Rollover Panel Layout',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_565bc9497949e',
							'label' => 'Hero Image',
							'name' => 'hero_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_565bc96a7949f',
							'label' => 'Headline',
							'name' => 'headline',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_565bc96f794a0',
							'label' => 'Full Height',
							'name' => 'full_height',
							'type' => 'true_false',
							'instructions' => 'If "True", the content area takes up 100% of the screen\'s visual height. Works best on the home page.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
						),
						array (
							'key' => 'field_565bc97b794a1',
							'label' => 'Rollover Panels',
							'name' => 'rollover_panels',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Rollover Panel',
							'sub_fields' => array (
								array (
									'key' => 'field_56649f05dac23',
									'label' => 'Custom Title',
									'name' => 'custom_title',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56649f51dac25',
												'operator' => '==',
												'value' => 'targets',
											),
										),
										array (
											array (
												'field' => 'field_56649f51dac25',
												'operator' => '==',
												'value' => 'page',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
								),
								array (
									'key' => 'field_565bc9a8794a2',
									'label' => 'Headline',
									'name' => 'headline',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56649f05dac23',
												'operator' => '==',
												'value' => '1',
											),
											array (
												'field' => 'field_56649f51dac25',
												'operator' => '==',
												'value' => 'targets',
											),
										),
										array (
											array (
												'field' => 'field_56649f05dac23',
												'operator' => '==',
												'value' => '1',
											),
											array (
												'field' => 'field_56649f51dac25',
												'operator' => '==',
												'value' => 'page',
											),
										),
										array (
											array (
												'field' => 'field_56649f51dac25',
												'operator' => '==',
												'value' => 'none',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_56649f51dac25',
									'label' => 'Link Type',
									'name' => 'link_type',
									'type' => 'select',
									'instructions' => 'Where would you like this panel to link?',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'none' => 'No Link',
										'targets' => 'Targets',
										'page' => 'Page',
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'disabled' => 0,
									'readonly' => 0,
								),
								array (
									'key' => 'field_56649c76d0153',
									'label' => 'Destination - Targets',
									'name' => 'destination',
									'type' => 'taxonomy',
									'instructions' => 'Destination the user arrives at when clicking on this panel.',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56649f51dac25',
												'operator' => '==',
												'value' => 'targets',
											),
										),
									),
									'wrapper' => array (
										'width' => 20,
										'class' => '',
										'id' => '',
									),
									'taxonomy' => 'target',
									'field_type' => 'select',
									'allow_null' => 0,
									'add_term' => 0,
									'save_terms' => 0,
									'load_terms' => 0,
									'return_format' => 'object',
									'multiple' => 0,
								),
								array (
									'key' => 'field_56649f43dac24',
									'label' => 'Destination - Page',
									'name' => 'destination_page',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_56649f51dac25',
												'operator' => '==',
												'value' => 'page',
											),
										),
									),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'ui' => 1,
								),
								array (
									'key' => 'field_565fb7896432c',
									'label' => 'Main Image',
									'name' => 'main_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 5,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_565bc9b6794a3',
									'label' => 'Theme',
									'name' => 'theme',
									'type' => 'select',
									'instructions' => 'The background color of the panel',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 10,
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'darkteal' => 'Dark Teal',
										'grey' => 'Grey',
										'darkgrey' => 'Dark Grey',
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'disabled' => 0,
									'readonly' => 0,
								),
								array (
									'key' => 'field_565bc9f9794a4',
									'label' => 'Panel Width',
									'name' => 'panel_width',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 7,
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										50 => '50%',
										100 => '100%',
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'disabled' => 0,
									'readonly' => 0,
								),
								array (
									'key' => 'field_565bca15794a5',
									'label' => 'Hover Image',
									'name' => 'hover_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_565bcac5836e4',
									'label' => 'Content',
									'name' => 'content',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => 'wpautop',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_566491eb08389',
	'title' => 'News Items',
	'fields' => array (
		array (
			'key' => 'field_566491f0a0584',
			'label' => 'Target Audience',
			'name' => 'target_audience',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'target',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_5664b87afeee2',
			'label' => 'Similar Posts',
			'name' => 'similar_posts',
			'type' => 'repeater',
			'instructions' => 'Choose up to 3 Similar Posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5664b895feee3',
			'min' => '',
			'max' => 3,
			'layout' => 'table',
			'button_label' => 'Add Similar Post',
			'sub_fields' => array (
				array (
					'key' => 'field_5664b895feee3',
					'label' => 'Similar Post',
					'name' => 'similar_post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'news',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_566869e4bc308',
	'title' => 'Programs',
	'fields' => array (
		array (
			'key' => 'field_56686c8801934',
			'label' => 'Similar Articles Headline',
			'name' => 'similar_posts_headline',
			'type' => 'text',
			'instructions' => 'Appears above similar articles / posts. If not set, the default value is "Similar Articles."',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_566869f1f3c38',
			'label' => 'Similar Posts',
			'name' => 'similar_posts',
			'type' => 'repeater',
			'instructions' => 'Choose up to three similar posts to appear below the page content. If left blank, the page will pull from the related page taxonomy if that\'s set.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => 3,
			'layout' => 'table',
			'button_label' => 'Add Similar Posts',
			'sub_fields' => array (
				array (
					'key' => 'field_56686a16f3c39',
					'label' => 'Similar Post',
					'name' => 'similar_post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'news',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
		array (
			'key' => 'field_56686a654bb9f',
			'label' => 'Related Taxonomy',
			'name' => 'related_taxonomy',
			'type' => 'taxonomy',
			'instructions' => 'This page is related to a taxonomy (e.g, Off-Road, Road, Pedestrian, etc) but it is not a part of that taxonomy. Which taxonomy is this page related to?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'target',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_56686d15b4126',
			'label' => 'Display "See More" Button',
			'name' => 'display_button',
			'type' => 'true_false',
			'instructions' => 'If checked, a "See More" button will appear below the similar articles. This will automatically link to the related taxonomy\'s archive page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-programs.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_566e3f2d988e5',
	'title' => 'Sponsors',
	'fields' => array (
		array (
			'key' => 'field_56b0312a60349',
			'label' => 'Sponsorship Level',
			'name' => 'sponsorship_level',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Sponsorship Level',
			'sub_fields' => array (
				array (
					'key' => 'field_56b031436034a',
					'label' => 'Sponsorship Level Title',
					'name' => 'sponsorship_level_title',
					'type' => 'text',
					'instructions' => 'Platinum, Gold,	Silver, etc.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56b031576034b',
					'label' => 'Sponsorship Level Description',
					'name' => 'sponsorship_level_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56b031796034c',
					'label' => 'Sponsorship Level Sponsors',
					'name' => 'sponsorship_level_sponsors',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 66,
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Sponsor',
					'sub_fields' => array (
						array (
							'key' => 'field_56b0318a6034d',
							'label' => 'Name',
							'name' => 'name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56b031926034e',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_56b0319a6034f',
							'label' => 'Logo',
							'name' => 'logo',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_56b031ab60350',
							'label' => 'Sponsorship Amount',
							'name' => 'sponsorship_amount',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_57a76e5d6cc43',
							'label' => 'Sponsor Profile Link',
							'name' => 'sponsor_profile_link',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
					),
				),
			),
		),
		array (
			'key' => 'field_57a76e326cc42',
			'label' => 'Sponsor Profile Link Label',
			'name' => 'sponsor_profile_label',
			'type' => 'text',
			'instructions' => 'If a sponsor has a profile, this label is the text for the link to that profile.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Sponsor Profile',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-sponsors.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5666799cc8cde',
	'title' => 'Website Footer',
	'fields' => array (
		array (
			'key' => 'field_566679a290fcb',
			'label' => 'Footer Button List',
			'name' => 'footer_button_list',
			'type' => 'repeater',
			'instructions' => 'Appears at the top of the footer in the center column.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Footer Button',
			'sub_fields' => array (
				array (
					'key' => 'field_566679bb90fcc',
					'label' => 'Footer Button Label',
					'name' => 'footer_button_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_566679e290fcd',
					'label' => 'Footer Button Destination',
					'name' => 'footer_button_destination',
					'type' => 'select',
					'instructions' => 'Does this link to an internal page or an external page?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'internal' => 'Internal',
						'external' => 'External',
						'custom' => 'Custom',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_56667a0a90fce',
					'label' => 'Footer Button Destination - Internal',
					'name' => 'footer_button_destination_internal',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_566679e290fcd',
								'operator' => '==',
								'value' => 'internal',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_56667a2190fcf',
					'label' => 'Footer Button Destination - External',
					'name' => 'footer_button_destination_external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_566679e290fcd',
								'operator' => '==',
								'value' => 'external',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_56667be17a13a',
					'label' => 'Footer Button Destination - Custom',
					'name' => 'footer_button_destination_custom',
					'type' => 'select',
					'instructions' => 'Custom functions for buttons.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_566679e290fcd',
								'operator' => '==',
								'value' => 'custom',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'subscribe' => 'Subscribe',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
			),
		),
		array (
			'key' => 'field_56667a3f28b05',
			'label' => 'Footer Link List',
			'name' => 'footer_link_list',
			'type' => 'repeater',
			'instructions' => 'Appears at the bottom of the footer. Links will be distributed evenly into three columns from left to right in desktop view and will stack on smaller devices.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Footer Link',
			'sub_fields' => array (
				array (
					'key' => 'field_56667a3f28b06',
					'label' => 'Footer Link Label',
					'name' => 'footer_link_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56667a3f28b07',
					'label' => 'Footer Link Destination',
					'name' => 'footer_link_destination',
					'type' => 'select',
					'instructions' => 'Does this link to an internal page or an external page?',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'internal' => 'Internal',
						'external' => 'External',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_56667a3f28b08',
					'label' => 'Footer Link Destination - Internal',
					'name' => 'footer_link_destination_internal',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56667a3f28b07',
								'operator' => '==',
								'value' => 'internal',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_56667a3f28b09',
					'label' => 'Footer Link Destination - External',
					'name' => 'footer_link_destination_external',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_56667a3f28b07',
								'operator' => '==',
								'value' => 'external',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_56667ccdbd11a',
			'label' => 'Footer Contact Info',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Appears in the footer of every page.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_56667cffbd11b',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '(415) 367 3469',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56667d19bd11c',
			'label' => 'Email Address',
			'name' => 'email_address',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'info@marinbike.org',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_56667d2bbd11d',
			'label' => 'Mailing Address',
			'name' => 'mailing_address',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'P.O. Box 1115<br/>
Fairfax, CA 94978',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56667d3fbd11e',
			'label' => 'Physical Address',
			'name' => 'physical_address',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '733 Center Blvd.<br/>
Fairfax, CA 94930',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_568060a18980e',
			'label' => 'Google Analytics Snippet',
			'name' => 'google_analytics_snippet',
			'type' => 'textarea',
			'instructions' => 'Copy / Paste Google Analytics Snippet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<script type="text/javascript">
	var _gaq = _gaq || [];

	_gaq.push([\'_setAccount\', \'UA-25099470-1\']);

	_gaq.push([\'_trackPageview\']);

	(function() {

		var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;

		ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';

		var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);


	})();
</script>',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57a799a69b1de',
			'label' => 'Copyright',
			'name' => 'copyright',
			'type' => 'text',
			'instructions' => 'Appears at bottom of page. Year is generated automatically and updated.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Marin County Bicycle Coalition. All Rights Reserved.',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57a799be9b1df',
			'label' => 'Footer Message',
			'name' => 'footer_msg',
			'type' => 'text',
			'instructions' => 'Free-form field for additional text at bottom of site. Appears below copyright.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Marin County Bicycle Coalition is a 501(c) (3) non-profit organization',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5668672c76f03',
	'title' => 'Page & Post',
	'fields' => array (
		array (
			'key' => 'field_566867567c0bd',
			'label' => 'Subheading',
			'name' => 'subheading',
			'type' => 'text',
			'instructions' => 'Appears above the title. If left blank, the subheading matches the page taxonomy (e.g, "Off Road", "Pedestrian", etc). If no Taxonomy is available, the subheading matches the page\'s parent category (e.g, "News").',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_567a1849d5f59',
			'label' => 'Display Events',
			'name' => 'show_events',
			'type' => 'true_false',
			'instructions' => 'Check the box & fill out the fields below if you would like to cross-reference events to this page. The events listings will appear below the content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5680c69ef5d80',
			'label' => 'Events Title',
			'name' => 'events_title',
			'type' => 'text',
			'instructions' => 'Appears above the list of events. Optional.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_567a1849d5f59',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_567a1c25a85bf',
			'label' => 'Display Event Category',
			'name' => 'display_event_category',
			'type' => 'taxonomy',
			'instructions' => 'Choose which event categories you\'d like to display on this page.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_567a1849d5f59',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'tribe_events_cat',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'page-home.php',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'tribe_events',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'page-home.php',
			),
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'tribe_venue',
			),
			array (
				'param' => 'post_type',
				'operator' => '!=',
				'value' => 'tribe_organizer',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'excerpt',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'featured_image',
		8 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56805d8944e79',
	'title' => 'SEO',
	'fields' => array (
		array (
			'key' => 'field_56805d8fb1e72',
			'label' => 'Page Title',
			'name' => 'page_title',
			'type' => 'text',
			'instructions' => 'Page Title. If left blank, uses name of page plus "MCBC", e.g., "Events | MCBC"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 56,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56805dccb1e73',
			'label' => 'Meta Description',
			'name' => 'meta_description',
			'type' => 'text',
			'instructions' => 'Description used in meta tags. Should be unique per page and use specific keywords for this page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Description of this page.',
			'prepend' => '',
			'append' => '',
			'maxlength' => 160,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56805de0b1e74',
			'label' => 'Meta Keywords',
			'name' => 'meta_keywords',
			'type' => 'text',
			'instructions' => 'comma separated list of keywords / keyphrases for this page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'e.g, offroad, off road, mountain biking, mtb marin',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tribe_events',
			),
		),
	),
	'menu_order' => 9,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;